## 주석부분은 커밋하지 말것 주석풀고 사용할것
graphql:
  spqr:
    gui:
      enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ##JDBC URL##
    username: ##DB ID##
    password: ##DB PASSWORD##